# This is an example configuration for Docker Compose. Make sure to atleast update
# the cookie secret & postgres database password.
#
# Some other recommendations:
# 1. To persist Postgres data, assign it a volume host location.
# 2. Split the worker service to adhoc workers and scheduled queries workers.
version: '2'
x-redash-service: &redash-service
  image: rodrigocadaval/redash:v10.1
  depends_on:
    - redis
  env_file: .env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 8
  scheduler:
    <<: *redash-service
    command: scheduler
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries"
      WORKERS_COUNT: 4
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 32
  worker-emails:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "emails default"
      WORKERS_COUNT: 2
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic"
      WORKERS_COUNT: 1
  worker_schemas:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "schemas"
      WORKERS_COUNT: 8
  redis:
    image: redis:5.0-alpine
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
networks:
  default:
    external:
      name: rodrigo
